### ISSUE TITLE
per-game code

### ISSUE THREAD

**Issue by rogerallen** [UW-NVIDIA-CAPSTONE/NVIDIA_Client#2]
I would definitely like to see coding in a more general manner than: `if (current_game == "INSIDE")` 

https://github.com/UW-NVIDIA-CAPSTONE/NVIDIA_Client/blob/master/WpfApplication1/MainWindow.xaml.cs#L155

A structure that abstracts game info into a configuration file would be much more scalable.

**Comment by DevinStoen** [comment]
I see, that is something I will move toward this next week.
